config/routes.rb
Rails.application.routes.draw do
  root :to => 'wish_lists#index'
  mount ShopifyApp::Engine, at: '/'
  resources :app_configurations, :except => [:new, :create, :destroy, :show]
  resources :wish_list_integrations, :except => [:edit, :update, :destroy, :show, :new, :create, :index] do
  	collection do
  		post    :create_with_list
      get     :customer_wish_list_view
      delete  :delete_wish_list
  	end
  end
  resources :wish_lists, :except => [:edit, :update, :destroy, :show, :new, :create] do
  	collection do
  		get       :wish_list_by_customer
			get 	    :wish_list_by_product
      delete    :remove_wishlist_item
      delete    :remove_customer_wishlist_item
      delete    :remove_product_wishlist_item
  	end
  end
  resources :wish_list_reports, :except => [:edit, :update, :destroy, :show, :new, :create] do
  	collection do
  		get 	:excel_report
  	end
  end
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController

	def index
    # if params[:shop].present?
    #   if params[:shop].blank?
    #     redirect_to("http://www.google.com/")
    #   else
    #     @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:shop_domain => params[:shop]).order("id DESC")
    #   end
    # else
    #   redirect_to("http://www.google.com/")
    # end
    @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:shop_domain => params[:shop]).order("id DESC")
    # @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).order("id DESC")
  end

  def wish_list_by_customer
    @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:shop_domain => params[:shop], :customer_id => params[:customer_id]).order("id DESC")
    # @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:customer_id => params[:customer_id]).order("id DESC")
  end

  def wish_list_by_product
  	@wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:shop_domain => params[:shop], :product_id => params[:product_id]).order("id DESC")
    # @wish_lists = UserWishList.paginate(:page => params[:page], :per_page => 30).where(:product_id => params[:product_id]).order("id DESC")
  end

  def remove_wishlist_item
    wish_list = UserWishList.find(params[:id])
    wish_list.destroy
    flash[:success] = "Deleted Successfully"
    redirect_to :back
  end

  def remove_customer_wishlist_item
    wish_list = UserWishList.find(params[:id])
    wish_list.destroy
    flash[:success] = "Deleted Successfully"
    redirect_to :back
  end

  def remove_product_wishlist_item
    wish_list = UserWishList.find(params[:id])
    wish_list.destroy
    flash[:success] = "Deleted Successfully"
    redirect_to :back
  end

end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/wish_lists/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Wishlist" });
     });
  </script>
<% end %>
<div class="col-sm-12">
  <h2 class="text-center">Wish List</h2>
  <div class="table-responsive">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th class="col-sm-2">Product Image</th>
          <th class="col-sm-2">Product Title</th>
          <th>Product SKU</th>
          <th>Barcode</th>
          <th>Customer Email</th>
          <th>Customer Name</th>
          <th>Date</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% if @wish_lists.count > 0 %>
          <% @wish_lists.each do |wish_list| %>
            <tr>
              <td class="col-sm-2">
                <img src="<%= wish_list.product_image %>" style="width: 100px;">
              </td>
              <td class="col-sm-2"><%= wish_list.product_title %></td>
              <td><%= link_to "#{wish_list.product_sku}", wish_list_by_product_wish_lists_path(:shop => params[:shop], :product_id => wish_list.product_id) %></td>
              <td><%= wish_list.barcode %></td>
              <td><%= link_to "#{wish_list.customer_email}", wish_list_by_customer_wish_lists_path(:shop => params[:shop], :customer_id => wish_list.customer_id) %></td>
              <td><%= wish_list.customer_name %></td>
              <td>
                <% if wish_list.wish_list_date.nil? %>
                  <%= "-" %>
                <% else %>
                  <%= wish_list.wish_list_date.strftime("%d-%m-%Y") %>
                <% end %>
                
              </td>
              <td class="text-center">
                <%= link_to remove_wishlist_item_wish_lists_path(:shop => params[:shop], :id => wish_list.id), method: :delete do %>
                <i class="glyphicon glyphicon-remove-circle"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="7" class="text-center"> No History Found </td>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @wish_lists %>
  </div>
  <br>
</div>

app/views/wish_lists/wish_list_by_customer.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Wishlist - by Customers" });
     });
  </script>
<% end %>
<div class="col-sm-12">
  <h2 class="text-center">Manage Wishlist - by Customers</h2>
  <div class="table-responsive">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th class="col-sm-2">Product Image</th>
          <th class="col-sm-2">Product Title</th>
          <th>Product SKU</th>
          <th>Barcode</th>
          <th>Customer Email</th>
          <th>Customer Name</th>
          <th>Date</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% if @wish_lists.count > 0 %>
          <% @wish_lists.each do |wish_list| %>
            <tr>
              <td class="col-sm-2">
                <img src="<%= wish_list.product_image %>" style="width: 100px;">
              </td>
              <td class="col-sm-2"><%= wish_list.product_title %></td>
              <td><%= wish_list.product_sku %></td>
              <td><%= wish_list.barcode %></td>
              <td><%= wish_list.customer_email %></td>
              <td><%= wish_list.customer_name %></td>
              <td><%= wish_list.wish_list_date.strftime("%d-%m-%Y") %></td>
              <td class="text-center">
                <%= link_to remove_customer_wishlist_item_wish_lists_path(:shop => params[:shop], :id => wish_list.id, :customer_id => wish_list.customer_id), method: :delete do %>
                <i class="glyphicon glyphicon-remove-circle"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="7" class="text-center"> No History Found </td>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @wish_lists %>
  </div>
  <br>
</div>

app/views/wish_lists/wish_list_by_product.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Wishlist - by Products" });
     });
  </script>
<% end %>
<div class="col-sm-12">
  <h2 class="text-center">Manage Wishlist - by Products</h2>
  <div class="table-responsive">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th class="col-sm-2">Product Image</th>
          <th class="col-sm-2">Product Title</th>
          <th>Product SKU</th>
          <th>Barcode</th>
          <th>Customer Email</th>
          <th>Customer Name</th>
          <th>Date</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% if @wish_lists.count > 0 %>
          <% @wish_lists.each do |wish_list| %>
            <tr>
              <td class="col-sm-2">
                <img src="<%= wish_list.product_image %>" style="width: 100px;">
              </td>
              <td class="col-sm-2"><%= wish_list.product_title %></td>
              <td><%= wish_list.product_sku %></td>
              <td><%= wish_list.barcode %></td>
              <td><%= wish_list.customer_email %></td>
              <td><%= wish_list.customer_name %></td>
              <td><%= wish_list.wish_list_date.strftime("%d-%m-%Y") %></td>
              <td class="text-center">
                <%= link_to remove_product_wishlist_item_wish_lists_path(:shop => params[:shop], :id => wish_list.id, :product_id => wish_list.product_id), method: :delete do %>
                <i class="glyphicon glyphicon-remove-circle"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="7" class="text-center"> No History Found </td>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @wish_lists %>
  </div>
  <br>
</div>