config/routes.rb
Rails.application.routes.draw do
  root :to => 'wish_lists#index'
  mount ShopifyApp::Engine, at: '/'
  resources :app_configurations, :except => [:new, :create, :destroy, :show]
  resources :wish_list_integrations, :except => [:edit, :update, :destroy, :show, :new, :create, :index] do
  	collection do
  		post    :create_with_list
      get     :customer_wish_list_view
      delete  :delete_wish_list
  	end
  end
  resources :wish_lists, :except => [:edit, :update, :destroy, :show, :new, :create] do
  	collection do
  		get       :wish_list_by_customer
			get 	    :wish_list_by_product
      delete    :remove_wishlist_item
      delete    :remove_customer_wishlist_item
      delete    :remove_product_wishlist_item
  	end
  end
  resources :wish_list_reports, :except => [:edit, :update, :destroy, :show, :new, :create] do
  	collection do
  		get 	:excel_report
  	end
  end
end

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wish List</title>
    <link rel="icon" type="image/ico" href="wish-list.png" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Wish List</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          	<li class="wish_lists_path"><%= link_to  "Wish List", wish_lists_path(:shop => params[:shop]) %></li>
            <li class="wish_list_reports_path"><%= link_to  "Report", wish_list_reports_path(:shop => params[:shop]) %></li>
            <li class="app_configurations"><%= link_to  "Configurations", app_configurations_path(:shop => params[:shop]) %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div style="margin-top: 6%;">
      <div class="page-content">
        <div class="container-fluid">
          <%=render "shared/notices"%>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

<script type="text/javascript">
	$(function()
	{
		var path = window.location.pathname
		if (path == "/wish_lists") {
			$('.wish_lists_path').addClass('active')
			$('.wish_list_reports_path').removeClass('active')
      $('.app_configurations').removeClass('active')
		}
    else if (path == "/") {
      $('.wish_lists_path').addClass('active')
      $('.wish_list_reports_path').removeClass('active')
      $('.app_configurations').removeClass('active')
    }
    else if (path == "/app_configurations") {
      $('.wish_lists_path').removeClass('active')
      $('.wish_list_reports_path').removeClass('active')
      $('.app_configurations').addClass('active')
    }
    else if (path == "/wish_lists/wish_list_by_customer")
    {
      $('.wish_lists_path').addClass('active')
      $('.wish_list_reports_path').removeClass('active') 
      $('.app_configurations').removeClass('active')
    }
    else if (path == "/wish_lists/wish_list_by_product")
    {
      $('.wish_lists_path').addClass('active')
      $('.wish_list_reports_path').removeClass('active') 
      $('.app_configurations').removeClass('active')
    }
		else
		{
			$('.wish_list_reports_path').addClass('active')
			$('.wish_lists_path').removeClass('active')
      $('.app_configurations').removeClass('active')
		}
	});
</script>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>